name: 'Feature Request'
description: Suggest a feature for yacaba

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which yacaba parts are relevant/related to the feature request?
      options:
        - web
        - ios
        - android
        - windows
        - server
        - Don't known / other
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true
